services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=etl-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=etl-db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    depends_on:
      - database
    ports:
      - 8000:8000


  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

